services:
  docs:
    image: dj_tariff_local_docs
    container_name: dj_tariff_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./dj_tariff:/app/dj_tariff:z
    ports:
      - '9000:9000'
    command: /start-docs
