# Generated by Django 6.0.8 on 2026-08-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TariffNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('code', models.CharField(blank=True, db_index=True, help_text='Unformatted code (e.g., 010121000000). Null for Sections.', max_length=12, null=True)),
                ('name', models.TextField(help_text='Official Turkish description')),
                ('node_type', models.CharField(choices=[('SECTION', 'Bölüm'), ('CHAPTER', 'Fasıl'), ('HEADING', 'Pozisyon'), ('SUBHEADING', 'Alt Pozisyon'), ('GTIP', 'Gtip')], max_length=15)),
                ('description_detail', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tariff Node',
                'verbose_name_plural': 'Tariff Nodes',
                'indexes': [models.Index(fields=['code'], name='tariff_tari_code_a05177_idx'), models.Index(fields=['node_type'], name='tariff_tari_node_ty_3be567_idx')],
            },
        ),
    ]
