# Generated by Django 6.0.8 on 2026-08-08 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariffnode',
            name='description_detail',
        ),
    ]
