# Generated by Django 6.0.8 on 2026-08-12 12:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0002_remove_tariffnode_description_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffCodeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', models.DecimalField(decimal_places=2, help_text='Tax rate as a percentage.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('measurement_unit', models.CharField(choices=[('GT', 'Gross ton'), ('c/k', 'Karat (1 metrik karat=2*10-4 kg)'), ('ce/el', 'Hücre adedi'), ('ct/l', 'Ton başına taşıma kapasitesi(1)'), ('g', 'Gram'), ('gi F/S', 'Gram olarak fissile izotop'), ('kg H2O2', 'Kilogram olarak Hidrojen peroksit'), ('kg K2O', 'Kilogram olarak Potasyum oksit'), ('kg KOH', 'Kilogram olarak Potasyum hidroksit (kostik potas)'), ('kg met.am.', 'Kilogram olarak Metil aminler'), ('kg N', 'Kilogram olarak Azot'), ('Kg NaOH', 'Kilogram olarak Sodyum hidroksit (kostik soda)'), ('kg/net eda', 'Kilogram olarak kurutulmuş net ağırlık'), ('kg P2O5', 'Kilogram olarak Difosfor pentaoksit'), ('kg %90 sdt', 'Kilogram olarak % 90 kuru ürün'), ('kg U', 'Kilogram olarak Uranyum'), ('1000 kWh', '1000 kilovat saat'), ('l', 'Litre'), ('Kg C5H14CINO', 'Kilogram olarak Kolin klorür'), ('l alc. %100', 'Litre olarak saf alkol (%100)'), ('m', 'Metre'), ('m2', 'Metre kare'), ('m3', 'Metre küp'), ('1000 m3', '1000 Metre küp'), ('p/a', 'Çift'), ('p/st', 'Adet'), ('100 p/st', '100 Adet'), ('1000 p/st', '1000 Adet'), ('TJ', 'Terajul (Brüt kalori değeri)'), ('t. CO2', 'Ton CO2 (karbon dioksit) eşdeğeri')], help_text='Measurement unit for this tariff entry.', max_length=32)),
                ('notes', models.TextField(blank=True, help_text='Optional notes for this tariff entry.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tariff_node', models.OneToOneField(blank=True, help_text='Tariff node associated with this custom tariff metadata.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_detail', to='tariff.tariffnode')),
            ],
            options={
                'verbose_name': 'Custom Tariff Code',
                'verbose_name_plural': 'Custom Tariff Codes',
                'ordering': ['tariff_node__code'],
            },
        ),
    ]
