# Generated by Django 6.0.8 on 2026-08-13 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0004_bindingtariffinformation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariffcodedetail',
            options={'ordering': ['tariff_node__code'], 'verbose_name': 'Tariff Detail', 'verbose_name_plural': 'Tariff Details'},
        ),
        migrations.RenameIndex(
            model_name='bindingtariffinformation',
            new_name='tariff_bind_binding_31fb31_idx',
            old_name='tariffs_bin_binding_idx',
        ),
        migrations.RenameIndex(
            model_name='bindingtariffinformation',
            new_name='tariff_bind_valid_f_cb0e76_idx',
            old_name='tariffs_bin_valid_f_idx',
        ),
        migrations.AlterField(
            model_name='tariffcodedetail',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tax rate as a percentage.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tariffnode',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Unformatted code (e.g., 010121000000). Empty for Sections.', max_length=12),
            preserve_default=False,
        ),
    ]
