# Generated by Django 6.0.8 on 2026-08-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0005_alter_bindingtariffinformation_timestamps'),
        ('tariff', '0005_alter_tariffcodedetail_options_and_more'),
    ]

    operations = [
    ]
