# Generated by Django 6.0.8 on 2026-08-13 13:05

import apps.tariffs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariff', '0006_merge_20260813_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bindingtariffinformation',
            name='binding_number',
            field=models.CharField(help_text='Binding tariff information number (format: TR followed by 14 digits, e.g., TR340000250097).', max_length=16, unique=True, validators=[apps.tariffs.models.validate_binding_number]),
        ),
    ]
